slack:
    token: xoxp-xxxxxxxxxxxxxx    # slack API token
    reactions: false              # omit reactions if false
    joins_leaves: false           # omit channel joins/leaves if false

mail:
    fromAddress: '"My Slack" <my.slack@gmail.com>'
    smtp: smtp.gmail.com:587
    useTLS: true
    username: my.slack@gmail.com
    password: xxxxxxxxx

channels:
  exclude:
    ## excluded channels
    - dev-prs
  map:
    ## Maps channels to a particular email address
    general: users@my.project.org
    dev: dev@my.project.org
    random: users@my.project.org
  catchall:
    ## Any channel that is not explicitly mapped or blacklisted will map to this email address
    dev@my.project.org
