slack:
    token: xoxp-xxxxxxxxxxxxxx    # slack API token
    reactions: false              # omit reactions if false
    joins_leaves: false           # omit channel joins/leaves if false
    permalinks: false             # include permalinks for each message
    ignore:                       # ignore any message that starts with given text
      - 'Ignore message starting with this text'
      - 'Also ignore me'

mail:
    fromAddress: '"My Slack" <my.slack@gmail.com>'
    smtp: smtp.gmail.com:587
    useTLS: true
    username: my.slack@gmail.com
    password: xxxxxxxxx

channels:
  exclude:
    ## excluded channels
    - dev-prs
  include:
    ## Maps channels to a particular email address
    - general: users@my.project.org
    - dev: dev@my.project.org
    - random: users@my.project.org
  catchall:
    ## Any channel that is not explicitly mapped or excluded will map to this email address
    dev@my.project.org
